// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7PUlKmSCAQSn8C5mrcEpMSJJrhVyNvPs',
    appId: '1:303293730962:web:f8c6c5821ea48a6db9564b',
    messagingSenderId: '303293730962',
    projectId: 'we-chat-8ae12',
    authDomain: 'we-chat-8ae12.firebaseapp.com',
    storageBucket: 'we-chat-8ae12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByJvLS9JrFx_eht_GjsLpboW-_XKxztsQ',
    appId: '1:303293730962:android:8b76dfbafe22d802b9564b',
    messagingSenderId: '303293730962',
    projectId: 'we-chat-8ae12',
    storageBucket: 'we-chat-8ae12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVHy3vGBTgZYZOxckoYEI00TP7jHyAA3s',
    appId: '1:303293730962:ios:9e87b046494d46e6b9564b',
    messagingSenderId: '303293730962',
    projectId: 'we-chat-8ae12',
    storageBucket: 'we-chat-8ae12.appspot.com',
    androidClientId: '303293730962-22d0eiq3e5sp9fp7de13klmnh3tdhvog.apps.googleusercontent.com',
    iosClientId: '303293730962-bg1gjr3dk1j7hgfu00rgtvu1hbg7unli.apps.googleusercontent.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );
}
